// products.js - Centralized product data

export const products = [
  {
    id: 1,
    name: "Floral Galore",
    desc: "Beautiful handmade floral pattern scrunchie with silk fabric",
    price: "₹1,299",
    originalPrice: "₹1,599",
    img: "https://i.pinimg.com/1200x/54/f7/eb/54f7ebba3580d751a07f383297650a35.jpg",
    category: "Hair",
    colors: ["#8B9DC3", "#A8D8D8", "#F4A6A6", "#DDA0DD"],
    sizes: ["XS", "S", "M"],
    details: {
      material: "Poly Cotton, Silk Satin",
      care: "Machine Wash, Gentle or Delicate",
      weight: "80gm (+/-) 10gm",
      style: "Gentle",
    },
    images: [
      "/api/placeholder/400/500",
      "/api/placeholder/400/500",
      "/api/placeholder/400/500",
      "/api/placeholder/400/500",
    ],
    description:
      "This clip is comfortable, easy and designed for the girl who's eyes are as deep as the ocean and her beauty is as alluring as sea. The product is comfortable because it is cut in a regular neckline that is pleated.",
  },
  {
    id: 2,
    name: "Gold Hoop Earrings",
    desc: "Elegant gold-plated hoop earrings with premium finish",
    price: "₹799",
    originalPrice: "₹999",
    img: "https://i.pinimg.com/1200x/57/ee/82/57ee82779c8d830bff10c326308f77d5.jpg",
    category: "Hair",
    colors: ["#FFD700", "#C0C0C0", "#CD7F32"],
    sizes: ["One Size"],
    details: {
      material: "Gold Plated Brass",
      care: "Wipe with soft cloth",
      weight: "15gm",
      style: "Classic",
    },
    images: [
      "/api/placeholder/400/500",
      "/api/placeholder/400/500",
      "/api/placeholder/400/500",
    ],
    description:
      "These elegant hoop earrings are perfect for any occasion. Made with high-quality gold plating that won't tarnish easily.",
  },
  {
    id: 3,
    name: "Honey Bee",
    desc: "Classic pearl necklace for special occasions",
    price: "₹2,199",
    originalPrice: "₹2,599",
    img: "https://i.pinimg.com/1200x/31/67/9e/31679ea66ac9205e1460ed998b4c544f.jpg",
    category: "Hair",
    colors: ["#FFFFF0", "#F5F5DC"],
    sizes: ["16 inch", "18 inch", "20 inch"],
    details: {
      material: "Freshwater Pearls, Sterling Silver",
      care: "Store separately, avoid chemicals",
      weight: "25gm",
      style: "Classic",
    },
    images: [
      "/api/placeholder/400/500",
      "/api/placeholder/400/500",
      "/api/placeholder/400/500",
    ],
    description:
      "Timeless pearl necklace featuring lustrous freshwater pearls. Perfect for weddings, formal events, or adding elegance to everyday wear.",
  },
  {
    id: 4,
    name: "Ties that Bind",
    desc: "Delicate silver chain bracelet with charm pendants",
    price: "₹1,499",
    originalPrice: "₹1,799",
    img: "https://i.pinimg.com/1200x/3e/8a/94/3e8a94504365ff34334398c4693d9fd4.jpg",
    category: "Hair",
    colors: ["#C0C0C0", "#FFD700"],
    sizes: ["6 inch", "7 inch", "8 inch"],
    details: {
      material: "Sterling Silver",
      care: "Polish with silver cloth",
      weight: "12gm",
      style: "Trendy",
    },
    images: ["/api/placeholder/400/500", "/api/placeholder/400/500"],
    description:
      "Charming silver bracelet with delicate chain links and beautiful charm details. Adjustable size for perfect fit.",
  },
  {
    id: 5,
    name: "Velvet Scrunchie Set",
    desc: "Set of 3 velvet scrunchies in different colors",
    price: "₹399",
    originalPrice: "₹499",
    img: "https://i.pinimg.com/1200x/7b/2b/dc/7b2bdcbbc858899dc70bb8e9175d1db2.jpg",
    category: "Earrings",
    colors: ["#8B0000", "#000080", "#006400"],
    sizes: ["One Size"],
    details: {
      material: "Velvet, Elastic",
      care: "Hand wash only",
      weight: "30gm (set)",
      style: "Casual",
    },
    images: ["/api/placeholder/400/500", "/api/placeholder/400/500"],
    description:
      "Luxurious velvet scrunchies that are gentle on your hair. Set includes three beautiful colors perfect for any outfit.",
  },
  {
    id: 6,
    name: "Crystal Drop Earrings",
    desc: "Sparkling crystal drop earrings for evening wear",
    price: "₹1,099",
    originalPrice: "₹1,399",
    img: "https://i.pinimg.com/736x/c5/94/8e/c5948e2df12e96d8bb6f4ffd1f1ae8e9.jpg",
    category: "Earrings",
    colors: ["#FFFFFF", "#FFB6C1", "#E6E6FA"],
    sizes: ["One Size"],
    details: {
      material: "Austrian Crystal, Silver Base",
      care: "Store in jewelry box",
      weight: "8gm",
      style: "Elegant",
    },
    images: [
      "/api/placeholder/400/500",
      "/api/placeholder/400/500",
      "/api/placeholder/400/500",
    ],
    description:
      "Stunning crystal drop earrings that catch the light beautifully. Perfect for special occasions and evening events.",
  },
  {
    id: 7,
    name: "Crystal Drop Earrings",
    desc: "Sparkling crystal drop earrings for evening wear",
    price: "₹1,099",
    originalPrice: "₹1,399",
    img: "https://i.pinimg.com/1200x/cb/09/5c/cb095ce54a9617cc905139141c194d52.jpg",
    category: "Earrings",
    colors: ["#FFFFFF", "#FFB6C1", "#E6E6FA"],
    sizes: ["One Size"],
    details: {
      material: "Austrian Crystal, Silver Base",
      care: "Store in jewelry box",
      weight: "8gm",
      style: "Elegant",
    },
    images: [
      "/api/placeholder/400/500",
      "/api/placeholder/400/500",
      "/api/placeholder/400/500",
    ],
    description:
      "Stunning crystal drop earrings that catch the light beautifully. Perfect for special occasions and evening events.",
  },
  {
    id: 8,
    name: "Crystal Drop Earrings",
    desc: "Sparkling crystal drop earrings for evening wear",
    price: "₹1,099",
    originalPrice: "₹1,399",
    img: "https://i.pinimg.com/1200x/f7/1c/36/f71c36e8f3a7179d50beee807f4d99f9.jpg",
    category: "Necklaces",
    colors: ["#FFFFFF", "#FFB6C1", "#E6E6FA"],
    sizes: ["One Size"],
    details: {
      material: "Austrian Crystal, Silver Base",
      care: "Store in jewelry box",
      weight: "8gm",
      style: "Elegant",
    },
    images: [
      "/api/placeholder/400/500",
      "/api/placeholder/400/500",
      "/api/placeholder/400/500",
    ],
    description:
      "Stunning crystal drop earrings that catch the light beautifully. Perfect for special occasions and evening events.",
  },
  {
    id: 9,
    name: "Crystal Drop Earrings",
    desc: "Sparkling crystal drop earrings for evening wear",
    price: "₹1,099",
    originalPrice: "₹1,399",
    img: "https://i.pinimg.com/1200x/53/c0/60/53c060235c0f26a4c2bfc24a75f62979.jpg",
    category: "Accesories",
    colors: ["#FFFFFF", "#FFB6C1", "#E6E6FA"],
    sizes: ["One Size"],
    details: {
      material: "Austrian Crystal, Silver Base",
      care: "Store in jewelry box",
      weight: "8gm",
      style: "Elegant",
    },
    images: [
      "/api/placeholder/400/500",
      "/api/placeholder/400/500",
      "/api/placeholder/400/500",
    ],
    description:
      "Stunning crystal drop earrings that catch the light beautifully. Perfect for special occasions and evening events.",
  },
  {
    id: 10,
    name: "Crystal Drop Earrings",
    desc: "Sparkling crystal drop earrings for evening wear",
    price: "₹1,099",
    originalPrice: "₹1,399",
    img: "https://i.pinimg.com/736x/2e/fa/cc/2efacc52133271749bf909c104fb9319.jpg",
    category: "Accesories",
    colors: ["#FFFFFF", "#FFB6C1", "#E6E6FA"],
    sizes: ["One Size"],
    details: {
      material: "Austrian Crystal, Silver Base",
      care: "Store in jewelry box",
      weight: "8gm",
      style: "Elegant",
    },
    images: [
      "/api/placeholder/400/500",
      "/api/placeholder/400/500",
      "/api/placeholder/400/500",
    ],
    description:
      "Stunning crystal drop earrings that catch the light beautifully. Perfect for special occasions and evening events.",
  },
  {
    id: 11,
    name: "Crystal Drop Earrings",
    desc: "Sparkling crystal drop earrings for evening wear",
    price: "₹1,099",
    originalPrice: "₹1,399",
    img: "https://i.pinimg.com/736x/0f/6f/78/0f6f787a8b260706ac171e26beee4591.jpg",
    category: "Accesories",
    colors: ["#FFFFFF", "#FFB6C1", "#E6E6FA"],
    sizes: ["One Size"],
    details: {
      material: "Austrian Crystal, Silver Base",
      care: "Store in jewelry box",
      weight: "8gm",
      style: "Elegant",
    },
    images: [
      "/api/placeholder/400/500",
      "/api/placeholder/400/500",
      "/api/placeholder/400/500",
    ],
    description:
      "Stunning crystal drop earrings that catch the light beautifully. Perfect for special occasions and evening events.",
  },
];

export const categories = [
  "All",
  "Hair",
  "Earrings",
  "Necklaces",
  "Accesories",
];
